### ISSUE TITLE
Getting image bleed errors on every page, most of which do not contain images

### ISSUE THREAD

**Issue by jakpra** [acl-org/aclpubcheck#51] opened 2022-12-15 07:17 UTC
It's also excessive amounts of errors, possibly one for every line in the PDF.

This might have to do with some unqualified except statements in lines 215 and 269 of formatchecker.py.
There are also some improperly indented lines in those try-except blocks, but simply fixing the indentation does not solve the issue.

**Comment by crux82** [comment] 2022-12-15 14:07
Are you experiencing the same problem using the online version? 

https://colab.research.google.com/drive/1Sq6ilmrFUQpUFMkV71U8-Wf0madW-Uer?usp=sharing

I think this problem is related to #50 
Is it correct?

Bests

Danilo

**Comment by crux82** [comment] 2022-12-16 12:13
Since Colab downloads and runs the version from this GitHub repository, I can assume the problem is due to your environment. 

If you agree, I would ask you to close this issue. 

Bests

Danilo

**Closed** 2023-04-04 20:34 UTC
